name: flat_tree
description: Flat widget tree
version: 1.0.1
homepage: https://github.com/sla-000/flutter_flat_tree

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
